GET http://localhost:8000/api/gastos
###
GET http://localhost:8000/api/gastos/getMarcas
###
GET http://localhost:8000/api/gastos/getProvincias
###
GET http://localhost:8000/api/gastos/getZonas
###
GET http://localhost:8000/api/gastos/GetDireccionGastosGenerales
###
GET http://localhost:8000/api/gastos/GetDireccionGastos
###
GET http://localhost:8000/api/gastos/GetRazonIdByIdDireccion?id=1
###
GET http://localhost:8000/api/gastos/getGastosGenerales
###
GET http://localhost:8000/api/gastos/getAgendaGastos
###
GET http://localhost:8000/api/gastos/getAgendaGastosItems?id_agenda=1
###
GET http://localhost:8000/api/gastos/GetListadoDeCompras/0/0/0/0/3
###
GET http://localhost:8000/api/gastos/getTotalPresupuesto/5/2025
###
GET http://localhost:8000/api/gastos/getPresupuestos
###
POST http://localhost:8000/api/gastos/postGastosGenerales
Content-Type: application/json

{
    "importe" : "1500.23",
    "fecha_registro" : "2025-04-27T00:00:00Z",
    "periodo" : "2025-04-27T00:00:00Z",
    "id_usuario" : "1",
    "id_gasto" : "1",
    "id_direccion" : "1",
    "realizada" : "1",
    "detalle" : "Prueba de gasto",
    "id_tipo":"1",
    "id_marca":"1"
}
###
POST http://localhost:8000/api/gastos/postTipoProducto
Content-Type: application/json

{
    "tipo_producto" : "Prueba 4",
    "descripcion" : "Prueba de Tipo de Producto"
}
###
POST http://localhost:8000/api/gastos/postMarca
Content-Type: application/json

{
    "Marca" : "Prueba 4"
}
###
POST http://localhost:8000/api/gastos/postLocalidad
Content-Type: application/json

{
    "localidad" : "Prueba",
    "provincia" : "1",
    "zona" : "2"
}
###
POST http://localhost:8000/api/gastos/postZona
Content-Type: application/json

{
    "zona" : "Prueba"
}
###
POST http://localhost:8000/api/gastos/postAgendaGasto
Content-Type: application/json

{
    "descripcion" : "Descripcion Agenda 1",
    "fecha_alta" : "2025-05-17T16:45:00Z",
    "alerta":1,
    "fecha_limite":"2025-05-30T00:00:00",
    "id_usuario":1
}
###
POST http://localhost:8000/api/gastos/postAgendaGastoItem
Content-Type: application/json

{
    "id_tipo": 1,
    "id_marca" : 2,
    "cantidad" : 3,
    "importe" : 135.23,
    "periodo" : "2025-05-18T15:57:00Z",
    "importeporunidad" : 1,
    "realizada" : false,
    "detalle" : "Prueba de inserción Agenda Item",
    "id_agenda" : 9
}
###
POST http://localhost:8000/api/gastos/postGrabarPresupuesto
Content-Type: application/json

{
    "mes" : 1,
    "anio" : 2025,
    "importe" : "12556,23",
    "fecha_alta" : "2025-05-28T00:00:00Z",
    "id_usuario" : 1,
    "descripcion" : "Prueba Presupuesto"
}
###
DELETE http://localhost:8000/api/gastos/deleteGastoGeneral/30018
###
DELETE http://localhost:8000/api/gastos/deleteAgendaGasto/6
###
DELETE http://localhost:8000/api/gastos/deleteAgendaItem/1
###
DELETE http://localhost:8000/api/gastos/deletePresupuesto/1
###
PUT http://localhost:8000/api/gastos/putPresupuesto/3
Content-Type: application/json

{
    "id_presupuesto" : "3",
    "mes" : 3,
    "descripcion" : "Presupuesto Marzo",
    "anio" : 2025,
    "importe" : 100000.24
}
###
