GET http://localhost:8000/api/usuarios
###
GET http://localhost:8000/api/usuarios/4
###
POST http://localhost:8000/api/usuarios/
Content-Type: application/json

{
    "usuario":"martin",
    "password":"martin",
    "fecha_alta":"2025-04-26 21:48:00"
}
###
PUT http://localhost:8000/api/usuarios/5
Content-Type: application/json

{
    "usuario":"martin6",
    "password":"123456"
}
###
DELETE http://localhost:8000/api/usuarios/6
###
GET http://localhost:8000/api/usuarios/martin/martin